allow_terms:
  - evacuation
  - shelter
  - bottled water
  - cooling center
deny_terms:
  - medical diagnosis
  - evacuation by force
jargon_glossary:
  - term: "AER"
    plain: "Action Execution Rate (how often recommended actions are taken)"
  - term: "ECE"
    plain: "Expected Calibration Error (match between scores and outcomes)"
languages_supported: ["en", "ko"]
